# (APPENDIX) Függelék {-} 

# Megoldások {#megoldasok}

## Megoldások az \@ref(itt-kezdodik-1-exercise) feladatokhoz {#itt-kezdodik-1-exercise-solution}


> 1. Milyen online vagy nyomtat könyvek segítik az R elsajátítását? Próbáljuk összegyűjteni a magyar nyelvű könyveket is!

Az R könyvekkel kapcsolatban könnyen az lehet az érzésünk, hogy *túl sok a könyv, és túl kevés az idő*. Valóban tengernyi R könyv vásárolható meg, melyek többsége angol nyelvű. Elegendő a Springer [Use R!](https://www.springer.com/series/6991) könyvsorozatára gondolni, amely önmagában több mint 80 címet tartalmaz. Az Amazon-ról elérhető, 2020. januárja után [megjelent](https://www.amazon.com/s?k=r+statistics&i=stripbooks&rh=n%3A5&s=relevanceexprank&Adv-Srch-Books-Submit.x=39&Adv-Srch-Books-Submit.y=5&field-datemod=1&field-dateop=After&field-dateyear=2020&unfiltered=1&ref=sr_adv_b) könyvek száma is túl van a kétszázon.

Különösen értékesek lehetnek az online elérhető könyvek. Az idegen nyelvű könyvek tematikus gyűjteménye a [Big Book of R](https://www.bigbookofr.com/), míg az R erőforrásokról [saját listát](https://abarik.github.io/roforrasok/) is karbantartok.

A magyar nyelvű könyvek közül külön is felsorolunk néhányat:

* Reiczigel Jenő, Harnos Andrea, Solymosi Norbert (2021). *Biostatisztika nem statisztikusoknak*. Pars Kft., Nagykovácsi.
* Dinya Elek, Solymosi Norbert (2016). *Biometria a klinikumban 2.  Feladatok megoldása R-környezetben.* Medicina Kiadó.
* Münnich Ákos, Nagy Ágnes, Abari Kálmán. *Többváltozós statisztika pszichológus hallgatók számára.* Bölcsész Konzorcium, Debrecen, 2006. (http://psycho.unideb.hu/statisztika)
ISBN 963 9704 04 0

> 2. Térképezzük fel az online videókurzusokat is az R tanulásához!

A videókurzusok többsége is angol nyelvű, a [Youtube](https://www.youtube.com/results?search_query=r+statistics)-ról ingyenesen, de a [Udemy](https://www.udemy.com/) vagy a [datacamp](https://www.datacamp.com/) oldaláról előfizetés ellenében több száz kurzust is elérhetünk.

Az R-rel való ismerkedést kezdhetjük az [R a gyakorlatban](https://www.youtube.com/playlist?list=PLnmeQHnHYqv6ENGrdTXiE9YJrvHuxH2C9) videósorozatommal is.


> 3. A bevezető példa (*Két tanítási módszer összehasonlítása*) megoldásában a hipotézisvizsgálat alapján adjunk szöveges értékelést! 

A Mann-Whitney-próba alapján azt mondhatjuk, elegendő bizonyítékot találtunk arra, hogy a modern (Sprego) módszer eredményesebb (Mdn=0,36), mint a hagyományos (Mdn=0,66) tanítási módszer (W=24; p=0,001).
