# Need to install these packages
install.packages("bookdown")
install.packages("downlit")
install.packages("knitr")
install.packages("Rcmdr")
install.packages("DescTools")
install.packages("psych")
install.packages("summarytools")
install.packages("tidyverse")
install.packages("fun")
install.packages("apa")
install.packages("devtools")
devtools::install_github('achetverikov/apastats',subdir='apastats')
install.packages("apastats")
devtools::install_github("rempsyc/rempsyc")
install.packages("papaja")
install.packages("BSDA")
install.packages("nonpar")
install.packages("TeachingDemos")
install.packages("anytime")
install.packages("installr")
install.packages("RXKCD")
install.packages("fontawesome")
install.packages("dichromat")
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install()
BiocManager::install(c("GenomicFeatures", "AnnotationDbi"))
install.packages("HSAUR3")
install.packages("rio")
rio::install_formats()
install.packages("fivethirtyeight")
install.packages("moments")
install.packages("styler")
install.packages("ggthemes")
install.packages("gcookbook")
install.packages("extrafont")
install.packages("flextable")
install.packages("EnvStats")
# install.packages("xplorerr")  # interaktív elemzés
# xplorerr::app_inference()
